[package]
name = "rujak"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
dotenv = "0.15.0"
log = "0.4.26"
serde = "1.0.218"
serde_json = "1.0.140"
sqlx = "0.8.3"
tokio = "1.43.0"
tracing = "0.1.41"
