openapi: 3.0.0
info:
  title: Rujak API
  description: OpenAPI Specification for Rujak's Journal Management System
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local Development Server

paths:
  /api/auth/login:
    post:
      summary: User Login
      description: Authenticate user with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: securepassword
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIs..."
        "401":
          description: Unauthorized
  /api/submission:
    get:
      summary: Get all manuscript submissions
      description: Returns a list of manuscript submissions.
      responses:
        "200":
          description: A list of submissions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Rust in Academic Publishing"
                    status:
                      type: string
                      example: "Under Review"
